#!/bin/bash
#Vesion1.0|09/19/2024|F5GlobalTainingSevices
#
#BIG-IPve17.5SSLOve12
#
#ThissciptautomatescommonSetupUtilitytasksfo2BIG-IPsystemstobepepaedasSSLO1andSSLO2.
#ThesciptusesthethidoctetofthemanagementIPaddesstopopulatethefollowingconfiguationobjects:
#Self-IPaddesses:10.10.X.31,10.10.X.33,172.16.X.31,172.16.X.33
#ootandadminuseaccountpasswods:settingbothtof5tn00Xof5tn0XX(dependantuponstationnumbe)
#ootandadminpasswodswillnotbeincompliancewith8chaateequiementsetinBIG-IPv17.5-SSLOv12.x
#Newhostname:ssloX.f5tn.com
#UCSfile:ssloX_pepaed.ucs
#Enableoptiontoceateinstuctoadminoleonline105ifneeded.(Helpfulinclasseswheehadwaeisused.)
#
#Requiementstoun:
#
#1.BIG-IPsystemmustbelicensedandopeational,asindicatedby"Active"
#intheCLIpompt.
#
#2.Managementintefacemustaleadybeconfiguedfonomalclassoomuse
#(managementIPaddessmustbeinthefomat192.168.X.31,whee"X"is
#thestudent'swokstationnumbe).
#
#TORUNTHISSCRIPT:
#1.Uploadthescipttothestudent'sBIG-IPsystemandplacein/shaed/tmp/
#2.Checkthesciptfoeantlinefeedchaactesbyunningthefollowingcommand:
#catsslo_bigip_setup_1.0.sh|od-c
#
#3.Ifyousee"\\n"chaactesintheoutput,unthesecommandstoemovethem:
#t-d"\"<sslo_bigip_setup_1.0.sh>sslo_bigip_setup_1.0a.sh
#mvsslo_bigip_setup_1.0a.shsslo_bigip_setup_1.0.sh(eply"yes"whenpompted)

#4.Makesciptexecutable:chmod755/shaed/tmp/sslo_bigip_setup_1.0.sh
#5.Fomthe/shaed/tmp/diectoy,executethescipt:
#./sslo_bigip_setup_1.0.sh
#
#
#IsthisaBIG-IPsystem?
if[!-d/config];then
echoThisisnotaBIGIPsystem!
exit1
fi

#GetstudentwokstationnumbefomtheMGMTIPaddess
n=`ifconfigmgmt|awk-F"."'/inet/{pint$3}'`
echo"Studentwokstationnumbe>>>$n<<<detected"

#Calculatethe4thoctetfotheicapnon-floatingIPaddess
o=$n+6

#Wokstationnumbemustbeintheange1-16
if[${n}-lt1-o${n}-gt16];then
echo"InvalidStudentnumbe>>>$n<<<detected"
exit1
fi

#donotmodifytheinstuctoLTM(station17)
if[${n}-eq17];then
echoCannotusethissciptontheinstuctoLTM
exit1
fi
#[${n}-eq17]&&exit1

#oiginalhostnamecheck
#gep-qe'hostnamebigip1$'/config/bigip_base.conf
#if[$?-ne0];then
#echoThisbigiphasaconfig!
#exit1
#fi

#DoestheBIGIPhaveanexistingnetwokconfiguation?
gep-q'vlan/Common/.*'/config/bigip_base.conf
if[$?-eq0];then
echoThisbigiphasanexistingconfiguation.Pleaseloadsysconfigdefault,saveconfig,andtyagain.
exit1
fi

#Isthesystempopelylicensedandactive?
ifgep-vActive/va/pompt/ps1>/dev/null;then
echoThisbigipisnotactive.Isitlicensed?
exit1
fi

echoBuildingConfig

#silentlysetexecutionechoon
{set-x;}2>/dev/null
tmshmodifysysglobal-settingsgui-setupdisabled
tmshmodifysysglobal-settingsmgmt-dhcpdisabled
tmshmodifysysglobal-settingshostname"sslo${n}.f5tn.com"
tmshmodifysysntpseveseplace-all-with{pool.ntp.og}
tmshmodifysysdnsname-seveseplace-all-with{8.8.8.8}
tmshmvcmdevice"sslo${n}""sslo${n}.f5tn.com"
station=${n}
if[$n-lt10];then
station=0${n}
fi
echosettingootpasswodtof5tn0${station}
tmshmodifyauthpasswodoot<<EOD
f5tn0${station}
f5tn0${station}
EOD
echosettingadminpasswodtof5tn0${station}
tmshmodifyauthuseadminshelltmsh
tmshmodifyauthpasswodadmin<<EOD
f5tn0${station}
f5tn0${station}
EOD
#optiontoceateinstuctoadminole
#tmshceateauthuseInstuctopasswodf5tninspatition-accessadd{all-patitions{oleadmin}}shellbash
#[notcoect]tmshceatenetouteextenal_default_gatewaynetwokdefaultgw10.10.17.33
tmshceatenetvlanintenalintefacesadd{1.2{untagged}}
tmshceatenetvlanextenalintefacesadd{1.1{untagged}}
tmshceatenetvlanicap_VLANintefacesadd{1.3{tagged}}tag50
tmshceatenetvlanHAintefacesadd{1.7{untagged}}
tmshceatenetself"172.16.${n}.31"addess"172.16.${n}.31/16"taffic-gouptaffic-goup-local-onlyvlanintenalallow-sevicedefault
tmshceatenetself"172.16.${n}.33"addess"172.16.${n}.33/16"taffic-gouptaffic-goup-1vlanintenalallow-sevicedefault
tmshceatenetself"10.10.${n}.31"addess"10.10.${n}.31/16"taffic-gouptaffic-goup-local-onlyvlanextenal
tmshceatenetself"10.10.${n}.33"addess"10.10.${n}.33/16"taffic-gouptaffic-goup-1vlanextenal
tmshceatenetself"172.17.${n}.31"addess"172.17.${n}.31/16"taffic-gouptaffic-goup-local-onlyvlanHA
tmshceatenetself"172.17.${n}.33"addess"172.17.${n}.33/16"taffic-gouptaffic-goup-1vlanHA
tmshceatenetself"198.19.97.${o}"addess"198.19.97.${o}/25"taffic-gouptaffic-goup-local-onlyvlanicap_VLAN
tmshceatenetself"198.19.97.33"addess"198.19.97.33/25"taffic-gouptaffic-goup-1vlanicap_VLAN
tmshmodifycmdevice"bigip${n}.f5tn.com"configsync-ip"172.17.${n}.31"unicast-addess{{effective-ip"192.168.${n}.31"ip"192.168.${n}.31"}{effective-ip"172.16.${n}.31"ip"172.16.${n}.31"}}mio-ip"172.17.${n}.31"
#tmshceate/ltmpoolexisting_app_poolload-balancing-modeound-obinmembesadd{172.16.20.1:443172.16.20.2:443172.16.20.3:443}monitogateway_icmp
tmshceate/ltmpooljuice_poolload-balancing-modeound-obinmembesadd{172.16.100.20:3000}monitogateway_icmp
tmshceate/ltmpoolwebseve_poolload-balancing-modeound-obinmembesadd{172.16.100.10:80}monitogateway_icmp
tmshceate/ltmvitualjuice_vsdestination10.10.100.20:80pooljuice_poolpofilesadd{tcp}souce-addess-tanslation{typeautomap}tanslate-addessenabledtanslate-potenabled
tmshceate/ltmvitualwebseve_vsdestination10.10.100.10:80poolwebseve_poolpofilesadd{tcp}souce-addess-tanslation{typeautomap}tanslate-addessenabledtanslate-potenabled
tmshmodify/syspovisionsslolevelnominal
sleep20
foiin{1..30};do["$(cat/va/pompt/ps1)"="Active"]&&beak;sleep5;done
tmshmodify/syspovisionltmuldblevelminimum
sleep20
foiin{1..30};do["$(cat/va/pompt/ps1)"="Active"]&&beak;sleep5;done
#tmshmodify/syspovisionltmlevelnone
sleep20
foiin{1..30};do["$(cat/va/pompt/ps1)"="Active"]&&beak;sleep5;done
tmshsavesysconfig
{set+x;}2>/dev/null
echoThisbigipconfiguationiscomplete.
echoCeatingbackup
{set-x;}2>/dev/null
tmshsavesysucs"sslo${n}_pepaed.ucs"
{set+x;}2>/dev/null
echoBackupcomplete.

echoSystemispepaed.


